### ISSUE TITLE
Suggestion: 'Artboard changed' visual indicator UI

### ISSUE THREAD

**Issue by songcarver** [jacopocolo/p5-sketchplugin#21]
Although the console would provide heavier debugging abilities, I find myself just turning on and off something to see if p5 actually ran or not (since sometimes changing code can produce no result, or negligible). Some simple visual indicator for 'the artboard changed' might be useful for this. 

Thanks!

**Comment by jacopocolo** [comment]
That's a great idea. I didn't think it was possible but… I just tried and it's actually very simple. I’m not working a lot on this plugin lately but expect a tiny update in few days!

**Comment by jacopocolo** [comment]
@songcarver maybe something like this? I’m catching errors and displaying a notification — otherwise it just works. It seems better than having a success notification every time you run your code.

![error-message](https://user-images.githubusercontent.com/1939567/38634781-26fc7b6a-3d89-11e8-9e99-a82f53879260.gif)

**Comment by jacopocolo** [comment]
Implemented error handing in release 1.1.1. @songcarver, it's not exactly what you asked but let's see if it helps. I’m still considering a more subtle success message but it's not part of this release.

**Comment by songcarver** [comment]
Implementation works great for me.
